### ISSUE TITLE
Can't raise weapon while rappelling

### ISSUE THREAD

**Issue by rockurheart** [sethduda/AdvancedUrbanRappelling#8]
Installed the files on the server, command line is correct and we can all do the actions, but we cant raise our weapons during rappelling :/ any ideas?

edit: other mods I am using are: CBA, ACE3, ASR_AI3, Ares, CUP-Core&Maps, TFAR, TF47 Launchers, TRYK, ZEC (Zeus and Eden Templates)

**Comment by sethduda** [comment]
Make sure you have the addon enabled on the client side - weapons only work
when the addon is also enabled on the client side.

**Comment by rockurheart** [comment]
Alrighty will do that, thanks for the quick response!
